language: objective-c
xcode_project: M3U8Kit.xcodeproj
# xcode_workspace: <WORKSPACE_PLACEHOLDER>
xcode_scheme: M3U8Kit
env:
  global:
    - FRAMEWORK_NAME=M3U8Kit
before_install:
  - brew update
  - brew outdated carthage ||  upgrade carthage
  - gem install xcpretty
  
script:
  - xcodebuild -project $FRAMEWORK_NAME.xcodeproj -scheme $FRAMEWORK_NAME | xcpretty
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
  
after_success:
  - if [ "$FASTLANE_LANE" == "code_coverage" ]; then
     bash <(curl -s https://codecov.io/bash);
    fi

notifications:
  email: false
