name: Validation

on:
  release:
    types:
      - created

jobs:
  validation:
    name: Upload pods to Specs
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: push trunk
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push;pod trunk me clean-sessions --all
