name: Validation

on:
  release:
    types:
      - created

jobs:
  validation:
    name: Upload pods to Specs
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: push trunk
        run: |
          pod trunk push
